### ISSUE TITLE
Possible to use distrax for Dist?

### ISSUE THREAD

**Issue by nipunbatra** [patel-zeel/ajax#3]
Minor thing: would it be possible to use Distrax for distributions? Are there any main missing ones?

https://github.com/patel-zeel/advi_jax/blob/4d94918171fe8001a37a6475f0678d535b4df88d/advi_jax/advi.py#L3

**Comment by patel-zeel** [comment]
Apart from Dirichlet, it seems to have major distributions ([missing Beta was implemented](https://github.com/deepmind/distrax/pull/140) five days ago). I can switch to `distrax.Normal` in `advi.py` because `prior_dist` is anyway passed from outside to ADVI class and it can handle both `distrax` and `tfp` distributions.

**Comment by patel-zeel** [comment]
There are a bunch of bijectors and distributions missing from `distrax`. So for now, I have completely moved to `tfp` substrate of `jax`.
